from pathlib import Path
import shutil, textwrap, yaml, json, os

root=Path('C:/Users/zhang/WorkBuddy/2026-09-17-22-06-48/_sandbox6/source-code-reading-skill-v0.5.1')
# Restore intentionally lost but still useful v0.3 assets.
shutil.copy2('C:/Users/zhang/WorkBuddy/2026-09-17-22-06-48/_sandbox6/_v0.3/references/tracing/exploration-policy.md', root/'references/tracing/exploration-policy.md')
shutil.copy2('C:/Users/zhang/WorkBuddy/2026-09-17-22-06-48/_sandbox6/_v0.3/knowledge-sources/README.md', root/'knowledge-sources/README.md')

# Update main SKILL from v0.4 without replacing its detailed content.
skill=(root/'SKILL.md').read_text()
skill=skill.replace('version: 0.4.0','version: 0.5.1',1)
skill=skill.replace('# Source Code Reading Skill v0.4','# Source Code Reading Skill v0.5.1',1)
skill=skill.replace('## Stage 1 — Scope & Explore\n', '''## Progressive execution controls\n\nThe six-stage protocol defines the reasoning stages. This section defines the **entry/exit gates** that prevent over-reading and over-modeling. These controls do not replace the six stages.\n\n```text\n0 Scope\n  ↓\n1 Orient\n  ↓\n2 Minimum Model\n  ↓\n3 Pattern\n  ↓\n4 Trace\n  ↓\n5 Represent / Document\n  ↓\n6 Validate\n  ↓\nExpand only if a concrete gap remains\n```\n\n### Gate 0 — Scope\n\nDefine:\n- user question\n- target subsystem/topic\n- repository + revision/build context when material\n- expected depth\n- expected output\n\nExit when the target can be stated in 1–3 sentences.\n\n### Gate 1 — Orient\n\nFind only enough context to answer **where this topic sits in the system**:\n- subsystem boundary\n- neighboring subsystems\n- likely entry points\n- critical symbols/types\n- obvious tests/docs\n\nDo not reconstruct the whole system here.\n\n### Gate 2 — Minimum Knowledge Model\n\nBuild only the model required by the current question:\n\n```text\nSystem → Subsystem → Path/Scenario → Mechanism → Entity → Symbol\n```\n\nNot every task needs every node. Stop when no unresolved unknown blocks the next stage.\n\n### Gate 3 — Pattern\n\nChoose one dominant comprehension pattern and optional secondary patterns. Stop once the representation goal is clear.\n\n### Gate 4 — Trace\n\nTrace only the evidence required to close the central claims. Use `D1/D2/D3` depth and explicit trace boundaries.\n\n### Gate 5 — Representation / Document\n\nChoose the smallest useful set of views. Stop when the reader can navigate **concept → relation → source**.\n\n### Gate 6 — Validate\n\nValidate the result and return to the earliest affected stage rather than regenerating blindly.\n\n## Progressive depth\n\nUse four depth levels:\n\n- **L0 Orientation** — where the topic sits and what surrounds it.\n- **L1 Local model** — core entities, management/data relations, one representative path.\n- **L2 Source trace** — key functions/fields/state/lifecycle/concurrency/data movement.\n- **L3 Cross-cutting architecture** — broader subsystem relations, recovery, performance, trade-offs only when required.\n\n**Default: start at L1.** Enter L2/L3 only when a concrete unresolved question requires it.\n\n## Stage 1 — Scope & Explore\n''')
old='''## Evolution\n\nUser feedback and reviewed cases can produce **candidate rules**, but no rule becomes normative without regression against existing gold cases. Use `evolution/evolution-policy.md`.\n\nNever allow a model to silently rewrite its own rules. The safe loop is:\n\n```text\nFeedback\n  ↓\nFailure classification\n  ↓\nRule proposal\n  ↓\nRegression\n  ↓\nHuman/project approval\n  ↓\nAdopted rule\n```'''
new='''## Evolution\n\nUser feedback and reviewed cases can produce **candidate rules**, but no rule becomes normative without regression against existing gold cases. Use `evolution/evolution-policy.md`.\n\nNever allow a model to silently rewrite its own rules. The safe loop is:\n\n```text\nFeedback\n  ↓\nFailure classification\n  ↓\nCase\n  ↓\nCandidate rule\n  ↓\nRegression\n  ↓\nHuman/project approval\n  ↓\nAdopted rule\n```\n\n### Non-regression invariant for Skill versions\n\nA Skill version is an **incremental evolution**, not a clean-room rewrite. Default behavior is:\n\n```text\nPrevious release\n   +\nNew capability / correction\n   ↓\nCapability inventory\n   ↓\nBaseline comparison\n   ↓\nMinimal patch / additive merge\n   ↓\nRegression\n   ↓\nNew release\n```\n\nBefore releasing a new version:\n\n1. inventory the previous release's capabilities and files;\n2. compare the candidate against that baseline;\n3. preserve existing capabilities unless a removal is explicit;\n4. add the smallest change that solves the new problem;\n5. run integrity/regression checks;\n6. record changes in `CHANGELOG.md`.\n\nA removal requires an explicit deprecation/removal record with reason, replacement, and regression evidence. See `evolution/baseline-policy.md`.'''
assert old in skill
skill=skill.replace(old,new,1)
# Add extension boundary before Modes.
marker='## Modes\n'
insert='''## Core vs capability extensions\n\nKeep the normative Skill focused on stable cognitive/procedural rules. Do not turn every tool manual into a core rule.\n\n| Layer | Contents | Examples |\n|---|---|---|\n| Core Skill | reasoning protocol + canonical model + safety rules | architecture, pattern, traceability, representation, validation |\n| Capability extensions | extraction/runtime/analysis capabilities | Clang AST, CodeQL, Sourcegraph, perf, BPF, VTune |\n| Knowledge sources | external teachers of method/tool semantics | UML, C4, SEI, arc42, renderer docs |\n| Evolution assets | feedback/cases/regression/change process | gold cases, failures, candidate rules |\n\nThis separation keeps the Skill stable while allowing analysis capabilities to evolve independently.\n\n'''
assert marker in skill
skill=skill.replace(marker,insert+marker,1)
(root/'SKILL.md').write_text(skill)

# README
readme='''# Source Code Reading Skill v0.5.1\n\nA graph-first Agent Skill for understanding large C/C++ systems through progressive, source-grounded reasoning.\n\n## What v0.5.1 fixes\n\nThis release is built by **incremental merge on the complete v0.4 baseline**. It adds progressive execution gates and a non-regression evolution policy without deleting the architecture, knowledge-source, evolution, cases, diagram, tracing, validation, template, or example assets from v0.4.\n\nThe withdrawn v0.5 package was a regression because it rebuilt the package from a reduced subset and dropped previously established capabilities. v0.5.1 is the repaired additive release.\n\n## Core model\n\n```text\nCanonical Knowledge Graph\n├── Architecture View\n├── Path / Runtime View\n├── Topic View\n└── Source View\n```\n\nOne graph supports zooming:\n\n```text\nSystem → Subsystem → Path → Mechanism → Entity → Symbol → Code\n```\n\n## Execution\n\nThe six-stage protocol remains:\n\n```text\nScope & Explore\n→ Knowledge Model\n→ Pattern Recognition\n→ Traceability\n→ Representation & Document\n→ Validation & Orchestration\n```\n\nAn entry/exit gate layer keeps execution progressive:\n\n```text\nScope → Orient → Minimum Model → Pattern → Trace → Represent → Validate\n                                                ↘ expand only when needed\n```\n\n## Package structure\n\n```text\nSKILL.md\nreferences/\n  architecture-model.md\n  architecture-reconstruction.md\n  knowledge-model.md\n  patterns/\n  representation/\n  diagrams/\n  tracing/\n  validation/\n  document-policy.md\nknowledge-sources/\nevolution/\ncases/\ntemplates/\nexamples/\ntests/\n```\n\n## Evolution rule\n\nNew versions merge forward from the previous release by default. No existing capability may disappear silently. Any removal must be explicit, justified, and regression-tested.\n\nSee `evolution/baseline-policy.md` and `tests/test_skill_integrity.py`.\n'''
(root/'README.md').write_text(readme)

# New reference files.
(root/'references/execution-progressive.md').write_text('''# Progressive Execution Policy\n\n## Purpose\n\nPrevent an Agent from spending its budget reconstructing the whole repository before it can answer the current source-reading question.\n\n## Canonical order\n\n```text\nScope → Orient → Minimum Model → Pattern → Trace → Representation → Validate\n                                                     ↓\n                                           expand only on evidence gap\n```\n\nThe six canonical reasoning stages remain unchanged; these are entry/exit controls.\n\n## Gates\n\n| Gate | Minimum output | Exit condition |\n|---|---|---|\n| Scope | question + boundary | target is 1–3 sentences |\n| Orient | system location | can answer “where is this?” |\n| Minimum model | smallest sufficient graph | no blocking unknown |\n| Pattern | dominant comprehension question | representation goal is clear |\n| Trace | evidence-backed claims | central claims trace to source |\n| Representation | compact useful views | concept → relation → source is navigable |\n| Validation | checked result | no known central contradiction |\n\n## Depth levels\n\n- L0: orientation\n- L1: local model\n- L2: source trace\n- L3: cross-cutting architecture\n\nDefault is L1. Deepening requires a named unresolved question.\n\n## Anti-overengineering\n\nDo not:\n\n- read the whole repository by default;\n- build the complete architecture before a current task has a reason for it;\n- enumerate every entity or edge;\n- generate every possible diagram;\n- consult external sources when target evidence already answers the question;\n- duplicate the same explanation across graph, prose, and code.\n\n## Re-entry\n\n```text\nMissing context/evidence → Scope/Explore or Trace\nWrong model             → Knowledge Model\nWrong pattern           → Pattern Recognition\nBad visual/document     → Representation & Document\nCross-view inconsistency→ Validation + minimum affected stage\n```\n''')
(root/'references/extension-boundary.md').write_text('''# Core Skill vs Extensions\n\n## Principle\n\nThe core Skill should encode stable reasoning rules, not every concrete tool.\n\n## Core\n\n- six-stage reasoning protocol;\n- progressive execution gates;\n- canonical knowledge model;\n- architecture/path/topic/source integration;\n- pattern recognition;\n- claim/evidence/traceability;\n- representation policy;\n- validation;\n- evolution/non-regression rules.\n\n## Capability extensions\n\nTool-specific capabilities belong outside the normative core, for example:\n\n```text\nClang AST / LibTooling\nCodeQL\nSourcegraph\nDoxygen\nperf / BPF\nVTune\nstatic-analysis backends\nruntime tracing backends\n```\n\nExtensions may emit evidence that is consumed by the core model. They must not silently redefine source semantics.\n\n## Knowledge sources\n\nMethodology, standards, renderer docs, language guidance, and mature project examples belong under `knowledge-sources/`. They teach method and tool capability; the target repository remains authoritative for target implementation facts.\n\n## Evolution assets\n\nFeedback, gold cases, failure cases, candidate rules, and regression results belong under `cases/` and `evolution/`.\n''')
(root/'evolution/baseline-policy.md').write_text('''# Skill Evolution Baseline Policy\n\n## Core invariant\n\n**Evolution is merge-based, not rewrite-based.** A new version starts from the previous released asset set and preserves it by default.\n\n## Release procedure\n\n```text\nPrevious release\n      ↓\nCapability inventory\n      ↓\nBaseline file/feature comparison\n      ↓\nMinimal additive patch\n      ↓\nIntegrity regression\n      ↓\nSemantic regression\n      ↓\nChangelog\n      ↓\nRelease\n```\n\n## Required checks\n\n### 1. Capability inventory\n\nRecord capabilities, reference sets, templates, cases, examples, and tests from the baseline.\n\n### 2. File preservation\n\nEvery baseline file must still exist in the candidate unless it appears in an explicit approved-removal record.\n\n### 3. Capability preservation\n\nA file may survive while a capability disappears from it. Therefore compare both file inventory and a human-readable capability inventory.\n\n### 4. Minimal patch\n\nPrefer adding or editing the smallest relevant section. Do not rewrite unrelated references merely to simplify the package.\n\n### 5. Removal protocol\n\nA removal must record:\n\n```yaml\nremoval:\n  path: ""\n  capability: ""\n  reason: ""\n  replacement: ""\n  regression_evidence: []\n  approved: false\n```\n\n### 6. Regression\n\nAt minimum run the integrity test plus the semantic regression suite described in `evolution/regression.md`.\n\n## What counts as regression\n\nExamples:\n\n- knowledge-source registry disappears;\n- gold/failure cases disappear;\n- diagram selection catalog loses critical semantic distinctions;\n- trace depth or claim verification disappears;\n- document policy becomes too weak to guide a note;\n- architecture ↔ topic ↔ source integration is no longer explicit.\n\n## Versioning rule\n\nA corrective release may be `x.y.1` when the main purpose is restoring lost behavior without intentionally redesigning the model.\n''')
(root/'evolution/capability-inventory.md').write_text('''# Capability Inventory — v0.5.1\n\nBaseline: `v0.4.0`\nCandidate: `v0.5.1`\n\n| Capability | v0.4 | v0.5.1 | Action |\n|---|---|---|---|\n| Six-stage execution | yes | yes | preserved |\n| System Atlas | yes | yes | preserved |\n| Canonical graph / one-model-many-views | yes | yes | preserved |\n| Architecture ↔ topic integration | yes | yes | preserved |\n| Knowledge model + semantic relations | yes | yes | preserved |\n| Pattern catalog | yes | yes | preserved |\n| Diagram catalog | yes | yes | preserved |\n| Claim verification | yes | yes | preserved |\n| D1/D2/D3 trace depth | yes | yes | preserved |\n| Validation V1–V6 | yes | yes | preserved |\n| Document policy | yes | yes | preserved |\n| Knowledge-source registry | yes | yes | preserved |\n| Evolution policy | yes | yes | strengthened |\n| Gold / failure cases | yes | yes | preserved |\n| Anti-pattern library | yes | yes | preserved |\n| Progressive execution gates | no | yes | added |\n| Skill baseline / non-regression policy | no | yes | added |\n| Integrity test | no | yes | added |\n| Core vs extensions boundary | partial | yes | clarified |\n| General exploration policy | partially lost in v0.4 | yes | restored |\n''')
(root/'CHANGELOG.md').write_text('''# Changelog\n\n## 0.5.1 — Incremental repair release\n\n### Added\n- progressive execution gates: Scope → Orient → Minimum Model → Pattern → Trace → Represent → Validate;\n- progressive depth policy L0–L3;\n- Core Skill vs capability-extension boundary;\n- merge-based/non-regression evolution policy;\n- baseline capability inventory;\n- package integrity regression test;\n- restored general exploration policy from the earlier baseline.\n\n### Preserved\n- complete v0.4 architecture foundation and reconstruction method;\n- canonical knowledge model and architecture/path/topic/source integration;\n- diagram catalog and representation policy;\n- traceability and validation policies;\n- knowledge-source registry;\n- evolution rules, anti-patterns, gold/failure cases, and regression policy;\n- templates and examples.\n\n### Corrective note\n\nThe previously packaged `v0.5` was built from a reduced file set and therefore dropped established capabilities. It is treated as a regression and is **not** the baseline for further evolution. This release is based on the full `v0.4` asset set instead.\n''')
(root/'knowledge-sources/README.md').write_text((root/'knowledge-sources/README.md').read_text() + '\n\n## v0.5.1 maintenance note\n\nThis registry is part of the persistent Skill asset set and must not disappear during version evolution. Preserve it unless a removal is explicitly approved and regression-tested.\n')
(root/'templates/capability-inventory.yaml').write_text('''baseline:\n  version: ""\n  files: []\n  capabilities: []\n\ncandidate:\n  version: ""\n  files: []\n  capabilities: []\n\ncomparison:\n  added: []\n  preserved: []\n  changed: []\n  removed: []\n\napproved_removals: []\n\nregression:\n  integrity: pending\n  semantic: pending\n''')
(root/'templates/evolution-change.yaml').write_text('''evolution:\n  id: ""\n  baseline_version: ""\n  candidate_version: ""\n  change_type: additive | corrective | redesign | removal\n  trigger: ""\n  capabilities_added: []\n  capabilities_changed: []\n  capabilities_removed: []\n  baseline_preserved: true\n  regression_cases: []\n  approved: false\n''')
(root/'examples/progressive-execution-example.md').write_text('''# Progressive Execution Example\n\n## Topic\n\nPostgreSQL Buffer Lookup\n\n### Gate 0 — Scope\n\nQuestion: how does a buffer lookup locate the corresponding `BufferDesc` and reach the page?\n\n### Gate 1 — Orient\n\nLocate Buffer Manager, buffer mapping structures, and the read path. Do not yet inspect eviction, WAL, bgwriter, or recovery.\n\n### Gate 2 — Minimum model\n\n```text\nBuffer Manager\n  ↓\nBuffer Mapping / hash partition\n  ↓\nBufferDesc\n  ↓\nshared buffer page\n```\n\n### Gate 3 — Pattern\n\nDominant: **Resource / Cache / Index**.\nSecondary: Structural, Concurrency.\n\n### Gate 4 — Trace\n\nTrace only the key lookup, bucket/partition selection, `BufferDesc` resolution, and page access needed to answer the question.\n\n### Gate 5 — Represent\n\nUse one compact management/resource view plus selected source anchors.\n\n### Gate 6 — Validate\n\nCheck that the diagram does not imply ownership or a runtime sequence unsupported by the source.\n\n### Expand only when needed\n\nOnly after the central lookup is clear should the agent expand to replacement/victim selection, LWLock partitioning, I/O, or recovery.\n''')

# Integrity test
(root/'tests').mkdir(exist_ok=True)
(root/'tests/test_skill_integrity.py').write_text('''#!/usr/bin/env python3\n"""Compare a candidate Skill against a baseline and prevent silent file loss.\n\nUsage:\n  python tests/test_skill_integrity.py <baseline_dir> <candidate_dir>\n\nThe test intentionally checks preservation rather than requiring byte identity.\n"""\nfrom __future__ import annotations\nimport sys\nfrom pathlib import Path\n\n\ndef file_set(root: Path) -> set[str]:\n    return {str(p.relative_to(root)) for p in root.rglob('*') if p.is_file()}\n\n\ndef main() -> int:\n    if len(sys.argv) != 3:\n        print("usage: test_skill_integrity.py <baseline_dir> <candidate_dir>")\n        return 2\n    baseline = Path(sys.argv[1]).resolve()\n    candidate = Path(sys.argv[2]).resolve()\n    b = file_set(baseline)\n    c = file_set(candidate)\n    missing = sorted(b - c)\n    added = sorted(c - b)\n    if missing:\n        print("REGRESSION: baseline files missing from candidate:")\n        for x in missing:\n            print("  -", x)\n        return 1\n    print(f"PASS: preserved {len(b)} baseline files; added {len(added)} files")\n    if added:\n        print("ADDED:")\n        for x in added:\n            print("  +", x)\n    return 0\n\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n''')

# Approved-removals record is empty for this release.
(root/'evolution/approved-removals.yaml').write_text('''version: "0.5.1"\napproved_removals: []\n''')

# Audit report.
(root/'EVOLUTION_AUDIT.md').write_text('''# v0.1–v0.5 Evolution Audit\n\n## Executive conclusion\n\n- **v0.1 → v0.2:** normal additive evolution. Diagram/representation semantics were substantially expanded; no material capability loss detected.\n- **v0.2 → v0.3:** normal additive evolution. External knowledge-source registry was added.\n- **v0.3 → v0.4:** architecture/evolution capabilities were added, but two earlier assets were lost: the general `exploration-policy.md` and the `knowledge-sources/README.md`. The first is a material process capability and is restored here; the second is documentation-level and is also restored.\n- **v0.4 → v0.5:** material regression. The package was rebuilt from a much smaller subset, dropping architecture detail references, knowledge sources, evolution/cases, diagram catalog, tracing/validation/document policies, templates, and examples. The concepts were partially restated in a smaller `SKILL.md`, but the reusable rule assets themselves disappeared. This is not healthy evolution.\n\n## Important features restored/preserved in v0.5.1\n\n1. System Atlas + Canonical Knowledge Graph + one-model-many-views.\n2. Architecture → Path/Scenario → Mechanism → Entity → Symbol → Source integration.\n3. Detailed knowledge model and semantic relation families.\n4. Pattern catalog and representation/diagram selection policy.\n5. Historical diagram/tool decision knowledge.\n6. Claim/Evidence/Trace model, `FACT/INFERENCE/INTERPRETATION`, and `D1/D2/D3`.\n7. Validation V1–V6 and targeted re-entry.\n8. Document policy, source navigation, snippets, and reader checks.\n9. Knowledge-source registry and external-source authority boundaries.\n10. Gold/failure cases, anti-patterns, feedback taxonomy, rule proposals, regression.\n11. Progressive execution gates and L0–L3 depth controls.\n12. Merge-based Skill evolution with baseline inventory and integrity regression.\n\n## Deliberately treated as normal consolidation\n\nSome historical diagram material was shortened in v0.4 (for example, less-central legacy/optional visual forms). The core semantic distinctions and decision policy survived. These were not treated as material capability loss.\n\n## New hard invariant\n\n> A Skill version must preserve the previous release's capabilities by default. A new version is a merge, not a clean-room rewrite.\n''')

# Ensure executable bit for the test.
os.chmod(root/'tests/test_skill_integrity.py',0o755)
print('built', root)
